import Head from "next/head";
import Link from "next/link";
import s from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pages Router Practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ul className={s.list}>
          <li>
            <Link href="/Seoul">서울</Link>
          </li>
          <li>
            <Link href="/London">런던</Link>
          </li>
          <li>
            <Link href="/Paris">파리</Link>
          </li>
        </ul>
      </div>
    </>
  );
}
