import Head from "next/head";
import s from "@/styles/Home.module.css";
import { InferGetServerSidePropsType } from "next";
import { getCurrentWeather } from "@/utils/weather";
import CurrentWeatherItem from "@/components/CurrentWeatherItem";
import { getTime } from "@/utils/timeZone";

const cities = [
  { name: "서울", code: "seoul" },
  { name: "런던", code: "london" },
  { name: "파리", code: "paris" },
];

export const getServerSideProps = async () => {
  const citiesCode = cities.map((city) => city.code);

  const currentWeather = await Promise.all(
    citiesCode.map((code) => getCurrentWeather(code))
  );

  const time = await Promise.all(
    currentWeather.map((weather) => getTime(weather.location.tz_id))
  );
  return { props: { currentWeather, time } };
};

export default function Home({
  currentWeather,
  time,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Pages Router Practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>날씨 앱</h1>
        <ul className={s.list}>
          {cities.map((city, index) => (
            <CurrentWeatherItem
              key={city.code}
              cityCode={city.code}
              cityName={city.name}
              weather={currentWeather[index].current.condition.text}
              time={time[index].dateTime}
            />
          ))}
        </ul>
      </div>
    </>
  );
}
